name: Vulnerability checks
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
env:
  GO_VERSION: "~1.18"
defaults:
  run:
    shell: bash
jobs:
  vulnerability-check:
    name: "Vulnerability Check"
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Check for vulnerabilities
        run: govulncheck ./...
